export const labels = {
    AppName: "KidsBank",
    Next: 'Következő',
    SignUp: "Regisztáció",
    SignIn: "Bejelentkezés",
    AlreadyHaveAnAccount: "Már regisztrált?",
    Username: "Felhasználónév",
    Email: "Email",
    Password: "Jelszó",
    PasswordConfirm: "Jelszó megerősítése",
    ForgotPassword: "Elfelejtettem jelszót",
    or: "VAGY",
    AddNewFamilyMember: "Új családtag hozzáadása",
    Nickname: "Becenév",
    Age: "Kor",
    Points: "Pontok",
    Actions: "Műveletek",
    Save: "Mentés",
    StarterPoints: "Kezdő pontok",
    Modify: "Módosítás",
    DeleteFamilyMember: "Családtag törlése",
    DeleteFamilyMemberMessage: "Biztosan törölni szeretnéd a családtagot?",
    Cancel: "Mégse",
    Delete: "Törlés",
    AddNewTask: "Új feladat hozzáadása",
    TaskName: "Feladat neve",
    TaskValue: "Feladat értéke",
    Child: "Gyerek",
    Deadline: "Határidő",
    DeleteTask: "Feladat törlése",
    DeleteTaskMessage: "Biztosan törölni szeretnéd a feladatot?",
    Title: "Cím",
    Text: "Szöveg",
    AddNewWeeklyMeeting: "Új heti megbeszélés hozzáadása",
    AddNewReward: "Új jutalom hozzáadása",
    Reward: "Jutalom",
    RewardName: "Jutalom megnevezése",
    DeleteReward: 'Jutalom törlése',
    DeleteRewardMessage: 'Biztosan törölni szeretnéd a jutalmat?',
    Reedem: 'Beváltás',
    Complete: 'Teljesítés',

}