export const labels = {
    AppName: "KidsBank",
    Next: 'Következő',
    SignUp: "Regisztáció",
    SignIn: "Bejelentkezés",
    AlreadyHaveAnAccount: "Már regisztrált?",
    Username: "Felhasználónév",
    Email: "Email",
    Password: "Jelszó",
    PasswordConfirm: "Jelszó megerősítése",
    ForgotPassword: "Elfelejtettem jelszót",
    or: "VAGY",
    AddNewFamilyMember: "Új családtag hozzáadása",
    Nickname: "Becenév",
    Age: "Kor",
    Points: "Pontok",
    Actions: "Műveletek",
    Save: "Mentés",
    StarterPoints: "Kezdő pontok",
    Modify: "Módosítás",
    DeleteFamilyMember: "Családtag törlése",
    DeleteFamilyMemberMessage: "Biztosan törölni szeretnéd a családtagot?",
    Cancel: "Mégse",
    Delete: "Törlés",
}